package io.github.takenoha.towerdefense.tactical

/** Effect vocabulary supported by the first tactical-build implementation. */
enum class TacticalEffectType {
    DAMAGE_MULTIPLIER,
    ATTACK_INTERVAL_MULTIPLIER,
    RANGE_ADD,
    AREA_RADIUS_MULTIPLIER,
    CHAIN_COUNT_ADD,
    SLOW_STRENGTH_MULTIPLIER,
    BURN_DURATION_MULTIPLIER,
    SUPPORT_BUFF_MULTIPLIER,
    REPAIR_COST_MULTIPLIER,
    CORE_LOW_HP_DAMAGE_MULTIPLIER,
    CORE_LOW_HP_ATTACK_INTERVAL_MULTIPLIER,
    TOWER_DAMAGE_TAKEN_MULTIPLIER,
    DAMAGE_TO_BOSS_MULTIPLIER,
    DAMAGE_TO_HIGH_HP_MULTIPLIER,
    DAMAGE_TO_LOW_HP_MULTIPLIER,
    DAMAGE_TO_SLOWED_TARGET_MULTIPLIER,
    DAMAGE_TO_BURNING_TARGET_MULTIPLIER,
}
